---
- name: Tasks to run in the VM before installing the cluster
  hosts: sandbox
  gather_facts: no
  remote_user: admin
  become: yes
  tasks:

  - name: Wait for SSH
    wait_for_connection:
      timeout: 60

  - name: Disable cloud-init
    file:
       path: /etc/cloud/cloud-init.disabled
       state: touch

  - name: Add the SSH authorized key
    authorized_key:
      user: admin
      key: "{{ sandbox_key }}"
      state: present
    when: sandbox_key is defined

  - name: Install packages
    yum:
      name:
      - NetworkManager
      - docker
      - epel-release
      - iscsi-initiator-utils
      - python-rtslib
      - rsync
      - targetcli

  - name: Add admin to the docker group
    user:
      name: admin
      groups: dockerroot

  - name: Allow admin access to docker
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {
          "group": "dockerroot"
        }

  - name: Set the iSCSI initiator name
    copy:
      content: "InitiatorName={{ sandbox_initiator }}"
      dest: /etc/iscsi/initiatorname.iscsi

  - name: Create the directory for iSCSI LUN backing files
    file:
      path: /storage
      state: directory

  - name: Generate the iSCSI target configuration script
    template:
      src: target.j2
      dest: /root/target.txt

  - name: Run the iSCSI target configuration script
    shell: targetcli < /root/target.txt
    args:
      creates: /etc/target/saveconfig.json

  - name: Enable and start services
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
    - NetworkManager
    - docker
    - target
